package com.ibm.academia.apirest.enums;

public enum TipoTarjeta {
	BSMART,
	AFINITYCARD,
	CLASICA,
	OFFICEDEPOT,
	COSCO,
	BESTBUYBANAMEX,
	THEHOMEDEPOT,
	ORO,
	PLATINUM,
	CITIADVANTAGE,
	BANAEXTELETON,
	APAC,
	MARTICLASICACITIBANAMEX,
	AMERICADEPORTEISMO,
	PUMASDEPORTEISMO,
	TOLUCADEPORTEISMO,
	LAVERDEDEPORTEISMO,
	MARTIPREMIUMCITIBANAMEX
	
}
